# Generated by Django 6.0.2 on 2026-03-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador_avancado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocopadrao',
            name='obrigatorio',
            field=models.BooleanField(default=False, help_text='Indica se o bloco é obrigatório (não pode ser removido da minuta).'),
        ),
    ]
