# Generated by Django 6.0.2 on 2026-03-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador_avancado', '0002_blocopadrao_obrigatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutagerada',
            name='nome_interno',
            field=models.CharField(default='Novo Rascunho de Edital', max_length=200),
        ),
    ]
