# Generated by Django 6.0.2 on 2026-02-27 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinutaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('kind', models.CharField(choices=[('edital', 'Edital'), ('contrato', 'Contrato'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceholderField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('textarea', 'Texto longo'), ('date', 'Data'), ('email', 'Email'), ('number', 'Número'), ('currency', 'Moeda')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gerarMinuta.section')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='gerarMinuta.minutatemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['template', 'parent', 'order'], name='gerarMinuta_templat_0bb6d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemplatePlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_bindings', to='gerarMinuta.placeholderfield')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_placeholders', to='gerarMinuta.minutatemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('template', 'field')},
            },
        ),
    ]
